// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0sMaD4siqlGIvXZeKpM-bVEaKd6pS-o',
    appId: '1:128760753191:android:bb063ddf3d99bad2e87202',
    messagingSenderId: '128760753191',
    projectId: 'personal-finance-22c2a',
    databaseURL: 'https://personal-finance-22c2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-22c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZPGZvgnqO650ygnEjvQTLbL5VHusg7BI',
    appId: '1:128760753191:ios:a7126d345b3dca1de87202',
    messagingSenderId: '128760753191',
    projectId: 'personal-finance-22c2a',
    databaseURL: 'https://personal-finance-22c2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-22c2a.appspot.com',
    iosClientId: '128760753191-q2t35h7sirq87h3uk8fms45ugssfgla9.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceFlutter',
  );
}
